// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestOtransTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void abrirVideoYouTube() {
    driver.get("https://otranscribe.com/");
    driver.manage().window().setSize(new Dimension(1054, 818));
    driver.findElement(By.cssSelector(".start-ready")).click();
    driver.findElement(By.cssSelector(".alt-input-button")).click();
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys("https://www.youtube.com/watch?v=IkVFBYW4egs");
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys(Keys.ENTER);
  }
  @Test
  public void config() {
    driver.get("https://otranscribe.com/");
    driver.manage().window().setSize(new Dimension(1051, 815));
    driver.findElement(By.cssSelector(".fa-cog")).click();
    driver.findElement(By.cssSelector("li:nth-child(1) .add-combo")).click();
    driver.findElement(By.cssSelector("li:nth-child(1) .key-combo:nth-child(1) .fa")).click();
    driver.findElement(By.cssSelector("li:nth-child(5) .add-combo")).click();
    driver.findElement(By.cssSelector("li:nth-child(5) .key-combo:nth-child(1) .fa")).click();
    driver.findElement(By.cssSelector(".title")).click();
    driver.findElement(By.cssSelector(".fa-cog")).click();
    driver.close();
  }
  @Test
  public void idioma() {
    driver.get("https://otranscribe.com/");
    driver.manage().window().setSize(new Dimension(1051, 815));
    driver.findElement(By.id("curr-lang")).click();
    driver.findElement(By.cssSelector(".language-button:nth-child(6)")).click();
    driver.close();
  }
  @Test
  public void link() {
    driver.get("https://otranscribe.com/");
    driver.manage().window().setSize(new Dimension(1051, 815));
    driver.close();
  }
}
